### ISSUE TITLE
[Feature] Premade Pocket rooms

### ISSUE THREAD

**Issue by NPException** [NPException/Dimensional-Pockets#92]
Make a command that stores the current Pocket room content in a json file.

the json can later be used to generate pre-made pockets.

EDIT: keep #62 in mind when doing this

**Comment by thraaawn** [comment]
I wanted to do something similiar but utilize the already existing schematic file format.
E.g. https://github.com/Lunatrius/Schematica

**Comment by NPException42** [comment]
well, the more I think about it, I will probably use neither json nor Schematica

since this is not really intended to be edited by hand anyway, I will probably use a simple self invented file format.

I thought something like this:

1. scan each block line by line, layer by layer.
2. check the block/tile and grab all the data about it (id, meta, nbt)
3. assign an ID to that specific combination of data and store it in a map
4. write ID into file
5. append map with ID:data to file

so to read it in, I just read the file back out and I'm good

**Comment by NPException** [comment]
_I'm officially stopping development for Dimensional Pockets._

I think I'm scrapping this feature for good. This feature also won't be considered for [Dimensional Pockets 2](https://github.com/NPException/Dimensional-Pockets-2).
